{
  "auths": {
    "52.91.247.224:30080": {
      "auth": "JGFwcDpISFBWODZJRkFLS0VKRFBVWU1QOEdTMjZGTVhFV0xZS1pNVjU4QjZTNEM0RVVMT01URVBJOThPNjBRMExJMjFCMzNDVlNSRzYxVUNNV09JT1NBMjAwRTA1VTY2MjNIVzNJNUxSSlJKRjc0WENJMUtEOFNFV1I0U1A=",
      "email": ""
    }
  }
}
